from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import polars as pl
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import (
    HistGradientBoostingClassifier,
    HistGradientBoostingRegressor,
)
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    precision_score,
    r2_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
)

# ============================================================================
# Configuration
# ============================================================================

ML_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = ML_ROOT / "data"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

TRAINING_DATASET = PROCESSED_DATA_DIR / "training.parquet"

MODEL_DIR = ML_ROOT / "models"

COMPLEXITY_MODEL_PATH = MODEL_DIR / "complexity.joblib"

ADJOURNMENT_MODEL_PATH = MODEL_DIR / "adjournment.joblib"

DURATION_MODEL_PATH = MODEL_DIR / "duration.joblib"


RANDOM_STATE = 42

TEST_SIZE = 0.20


# ============================================================================
# Training schema
# ============================================================================

CATEGORICAL_FEATURES = [
    "case_type",
    "court",
    "jurisdiction",
    "stage",
]


NUMERICAL_FEATURES = [
    "document_word_count",
    "document_sentence_count",
    "section_count",
    "judge_count",
    "act_count",
    "precedent_count",
]


FEATURE_COLUMNS = CATEGORICAL_FEATURES + NUMERICAL_FEATURES


COMPLEXITY_TARGET = "complexity_score"

ADJOURNMENT_TARGET = "adjourned"

DURATION_TARGET = "duration_days"


# ============================================================================
# Dataset
# ============================================================================


def LoadDataset() -> pl.DataFrame:
    """
    Load the training dataset generated by labels.py.
    """

    if not TRAINING_DATASET.exists():
        raise FileNotFoundError(
            "Training dataset not found:\n"
            f"{TRAINING_DATASET}\n\n"
            "Run:\n"
            "    python -m ml.src.labels\n"
            "first."
        )

    df = pl.read_parquet(TRAINING_DATASET)

    if df.height == 0:
        raise ValueError("training.parquet contains zero rows.")

    return df


def ValidateDataset(
    df: pl.DataFrame,
) -> None:
    """
    Verify all required features and targets exist.
    """

    required = set(FEATURE_COLUMNS)

    required.update(
        {
            COMPLEXITY_TARGET,
            ADJOURNMENT_TARGET,
            DURATION_TARGET,
        }
    )

    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            "Training dataset is missing columns: " + ", ".join(sorted(missing))
        )


# ============================================================================
# Preprocessing
# ============================================================================


def CreatePreprocessor() -> ColumnTransformer:
    """
    Create the common preprocessing pipeline used by all three models.

    Categorical:
        missing-value handling
        one-hot encoding

    Numerical:
        median imputation
        standardization
    """

    categorical_pipeline = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="most_frequent",
                ),
            ),
            (
                "encoder",
                OneHotEncoder(
                    handle_unknown="ignore",
                    sparse_output=False,
                ),
            ),
        ]
    )

    numerical_pipeline = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median",
                ),
            ),
            (
                "scaler",
                StandardScaler(),
            ),
        ]
    )

    return ColumnTransformer(
        transformers=[
            (
                "categorical",
                categorical_pipeline,
                CATEGORICAL_FEATURES,
            ),
            (
                "numerical",
                numerical_pipeline,
                NUMERICAL_FEATURES,
            ),
        ],
        remainder="drop",
    )


# ============================================================================
# Models
# ============================================================================


def CreateComplexityModel() -> Pipeline:
    """
    Complexity is a continuous regression problem.

        X -> complexity_score [0, 100]
    """

    return Pipeline(
        steps=[
            (
                "preprocessor",
                CreatePreprocessor(),
            ),
            (
                "model",
                HistGradientBoostingRegressor(
                    learning_rate=0.08,
                    max_iter=250,
                    max_leaf_nodes=31,
                    l2_regularization=1.0,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )


def CreateAdjournmentModel() -> Pipeline:
    """
    Adjournment is a binary classification problem.

        X -> P(adjourned = 1)
    """

    return Pipeline(
        steps=[
            (
                "preprocessor",
                CreatePreprocessor(),
            ),
            (
                "model",
                HistGradientBoostingClassifier(
                    learning_rate=0.08,
                    max_iter=250,
                    max_leaf_nodes=31,
                    l2_regularization=1.0,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )


def CreateDurationModel() -> Pipeline:
    """
    Duration is a continuous regression problem.

        X -> duration_days
    """

    return Pipeline(
        steps=[
            (
                "preprocessor",
                CreatePreprocessor(),
            ),
            (
                "model",
                HistGradientBoostingRegressor(
                    learning_rate=0.08,
                    max_iter=250,
                    max_leaf_nodes=31,
                    l2_regularization=1.0,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )


# ============================================================================
# Evaluation
# ============================================================================


def EvaluateRegressor(
    name: str,
    model: Pipeline,
    x_test,
    y_test: np.ndarray,
) -> None:
    """
    Print regression metrics.
    """

    prediction = model.predict(x_test)

    mae = mean_absolute_error(
        y_test,
        prediction,
    )

    mse = mean_squared_error(
        y_test,
        prediction,
    )

    rmse = float(np.sqrt(mse))

    r2 = r2_score(
        y_test,
        prediction,
    )

    print()
    print(f"=== {name.upper()} ===")

    print(f"MAE  : {mae:.4f}")

    print(f"RMSE : {rmse:.4f}")

    print(f"R²   : {r2:.4f}")


def EvaluateClassifier(
    name: str,
    model: Pipeline,
    x_test,
    y_test: np.ndarray,
) -> None:
    """
    Print binary classification metrics.
    """

    prediction = model.predict(x_test)

    probabilities = model.predict_proba(x_test)[:, 1]

    accuracy = accuracy_score(
        y_test,
        prediction,
    )

    precision = precision_score(
        y_test,
        prediction,
        zero_division="warn",
    )

    recall = recall_score(
        y_test,
        prediction,
        zero_division="warn",
    )

    f1 = f1_score(
        y_test,
        prediction,
        zero_division="warn",
    )

    auc = roc_auc_score(
        y_test,
        probabilities,
    )

    print()
    print(f"=== {name.upper()} ===")

    print(f"Accuracy  : {accuracy:.4f}")

    print(f"Precision : {precision:.4f}")

    print(f"Recall    : {recall:.4f}")

    print(f"F1        : {f1:.4f}")

    print(f"ROC-AUC   : {auc:.4f}")


# ============================================================================
# Training
# ============================================================================


def TrainModels(
    df: pl.DataFrame,
) -> tuple[
    Pipeline,
    Pipeline,
    Pipeline,
]:
    """
    Train all three DocketIQ prediction models.
    """

    # -----------------------------------------------------------------------
    # sklearn works most conveniently with pandas DataFrames here because
    # ColumnTransformer selects columns by name.
    # -----------------------------------------------------------------------

    pandas_df = df.to_pandas()

    x = pandas_df[FEATURE_COLUMNS]

    y_complexity = pandas_df[COMPLEXITY_TARGET].to_numpy(dtype=np.float64)

    y_adjournment = pandas_df[ADJOURNMENT_TARGET].to_numpy(dtype=np.int8)

    y_duration = pandas_df[DURATION_TARGET].to_numpy(dtype=np.float64)

    # -----------------------------------------------------------------------
    # Generate ONE train/test split.
    #
    # All three models therefore see the same training cases and are
    # evaluated against the same test cases.
    #
    # Stratification uses the binary adjournment target.
    # -----------------------------------------------------------------------

    indices = np.arange(len(x))

    (
        train_indices,
        test_indices,
    ) = train_test_split(
        indices,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        shuffle=True,
        stratify=y_adjournment,
    )

    x_train = x.iloc[train_indices]

    x_test = x.iloc[test_indices]

    complexity_train = y_complexity[train_indices]

    complexity_test = y_complexity[test_indices]

    adjournment_train = y_adjournment[train_indices]

    adjournment_test = y_adjournment[test_indices]

    duration_train = y_duration[train_indices]

    duration_test = y_duration[test_indices]

    print()
    print(f"Training samples : {len(train_indices)}")

    print(f"Testing samples  : {len(test_indices)}")

    # =======================================================================
    # Complexity
    # =======================================================================

    print()
    print("Training complexity model...")

    complexity_model = CreateComplexityModel()

    complexity_model.fit(
        x_train,
        complexity_train,
    )

    EvaluateRegressor(
        name="Complexity",
        model=complexity_model,
        x_test=x_test,
        y_test=complexity_test,
    )

    # =======================================================================
    # Adjournment
    # =======================================================================

    print()
    print("Training adjournment model...")

    adjournment_model = CreateAdjournmentModel()

    adjournment_model.fit(
        x_train,
        adjournment_train,
    )

    EvaluateClassifier(
        name="Adjournment",
        model=adjournment_model,
        x_test=x_test,
        y_test=adjournment_test,
    )

    # =======================================================================
    # Duration
    # =======================================================================

    print()
    print("Training duration model...")

    duration_model = CreateDurationModel()

    duration_model.fit(
        x_train,
        duration_train,
    )

    EvaluateRegressor(
        name="Duration",
        model=duration_model,
        x_test=x_test,
        y_test=duration_test,
    )

    return (
        complexity_model,
        adjournment_model,
        duration_model,
    )


# ============================================================================
# Serialization
# ============================================================================


def SaveModels(
    complexity_model: Pipeline,
    adjournment_model: Pipeline,
    duration_model: Pipeline,
) -> None:
    """
    Save complete sklearn pipelines.

    The preprocessing logic is stored inside each joblib file, so inference
    only needs to construct a DataFrame with FEATURE_COLUMNS.
    """

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()
    print("Saving models...")

    joblib.dump(
        complexity_model,
        COMPLEXITY_MODEL_PATH,
        compress=3,
    )

    joblib.dump(
        adjournment_model,
        ADJOURNMENT_MODEL_PATH,
        compress=3,
    )

    joblib.dump(
        duration_model,
        DURATION_MODEL_PATH,
        compress=3,
    )

    print()
    print(f"Complexity  : {COMPLEXITY_MODEL_PATH}")

    print(f"Adjournment : {ADJOURNMENT_MODEL_PATH}")

    print(f"Duration    : {DURATION_MODEL_PATH}")


# ============================================================================
# Main
# ============================================================================


def main() -> None:

    print()
    print("=" * 72)
    print("DocketIQ Model Training")
    print("=" * 72)

    print()
    print(f"Dataset: {TRAINING_DATASET}")

    print("Loading dataset...")

    df = LoadDataset()

    print(f"Loaded {df.height} samples.")

    ValidateDataset(df)

    print()
    print("Training three models...")

    (
        complexity_model,
        adjournment_model,
        duration_model,
    ) = TrainModels(df)

    SaveModels(
        complexity_model,
        adjournment_model,
        duration_model,
    )

    print()
    print("=" * 72)
    print("Training complete")
    print("=" * 72)

    print()
    print("Generated:")

    print("  ml/models/complexity.joblib")

    print("  ml/models/adjournment.joblib")

    print("  ml/models/duration.joblib")

    print()
    print(
        "IMPORTANT: these models were trained against synthetic/proxy "
        "targets generated by labels.py."
    )

    print()


if __name__ == "__main__":
    main()
